### ISSUE TITLE
INDEX 성능 전후 비교 2 ( Artillery 부하 테스트 )

### ISSUE THREAD

**Issue by dlask913** [dlask913/vue3-spring-project#26]
### artillery 를 통한 부하테스트로 전후 조회 속도 비교하기

[ INDEX ] 
```sql
CREATE INDEX idx_messages_room_created ON Messages (room_id, created_at DESC); -- room 별 가장 최근 메시지를 조회하기 위해 생성
```

1. 더미 데이터 생성
```sql
-- 100만개의 더미 데이터 생성하는 쿼리
INSERT INTO Messages (room_id, sender_id, receiver_id, content, is_read, created_at)
WITH RECURSIVE cte (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM cte WHERE n < 1000000 -- 생성하고 싶은 더미 데이터의 개수
)
SELECT
    FLOOR(RAND() * 1000) + 1 AS room_id,  -- room_id는 1부터 1000까지의 랜덤 값
    FLOOR(RAND() * 1000) + 1 AS sender_id,  -- sender_id는 1부터 1000까지의 랜덤 값
    FLOOR(RAND() * 1000) + 1 AS receiver_id,  -- receiver_id는 1부터 1000까지의 랜덤 값
    CONCAT('Message content ', LPAD(n, 7, '0')) AS content,  -- content는 "Message content" + 숫자로 생성
    IF(RAND() < 0.5, 'Y', 'N') AS is_read,  -- is_read는 랜덤으로 'Y' 또는 'N'으로 생성
    TIMESTAMP(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 3650 + 1) DAY) + INTERVAL FLOOR(RAND() * 86400) SECOND) AS created_at  -- created_at은 랜덤한 날짜 및 시간
FROM cte;
```

2. 엔드포인트 요청하는 스크립트 작성
```yaml
config:
  target: "http://localhost:8080" 
  phases:
    - duration: 60  # 테스트 지속 시간 (초)
      arrivalRate: 10  # 초당 10개의 요청 생성
  payload:
    path: "users.csv"  # 테스트할 회원 ID 목록 파일
    fields:
      - "memberId"
scenarios:
  - flow:
      - get:
          url: "/rooms/{{ memberId }}"
```

3. 실행 결과 전후 비교 ( report-with-index.json & report-without-index.json )

- 인덱스 적용 (report-with-index.json)
  - p95 latency: 7ms
  - p99 latency: 9.5ms
  - 최대 응답 시간: 20ms
  - 평균 RPS: 9.93

- 인덱스 미적용 (report-without-index.json)
  - p95 latency: 460ms
  - p99 latency: 553ms
  - 최대 응답 시간: 1220ms
  - 평균 RPS: 9.93
