### ISSUE TITLE
도커 볼륨 마운트

### ISSUE THREAD

**Issue by dlask913** [dlask913/vue3-spring-project#27]
[문제점]
- 컨테이너 배포해서 파일 업로드 시 컨테이너 재시작하면 파일이 삭제됨

[해결방안]
- Docker 볼륨을 생성하고 컨테이너 내부 디렉토리에 마운트해서 컨테이너를 삭제해도 파일이 유지되도록 한다
- docker compose down 을 통해 컨테이너 삭제 후 새로 생성해도 데이터 유지

[사용방법]
1. 수동 생성
```shell
docker volume create vue3-spring # 볼륨 생성
docker run -d -v vue3-spring:/app/uploads --name [contaienr] [image] 
```
2. docker-compose.yml 를 통해 자동 생성
```yaml
services:
  mysql:
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: # 데이터 저장용
```
