### ISSUE TITLE
분산 환경에서의 동시성 이슈 테스트

### ISSUE THREAD

**Issue by dlask913** [dlask913/vue3-spring-project#38]
- 입찰 가격 입력 시에 이중화된 컨테이너에서도 동시성을 보장할 수 있는 지 테스트
- 테스트 코드로는 단일 인스턴스에 대한 테스트만 가능하기 때문에 Artillery 사용

### [Artillery 로 분산 환경에서의 동시성 이슈 테스트하기]
1. /bid 호출 전에 product 와 member 에 대한 데이터 Insert 하기
```sql
INSERT INTO Products (title, content, category, standard_price, owner_id, deadline) VALUES ('title', 'content', 'FURNITURE', 2000, 126, NULL);
INSERT INTO Members (email, username, password, address) VALUES ('user0@test.com', 'user0', 'password1', 'Seoul');
..
INSERT INTO Bid_History (bid_price, customer_id, product_id) VALUES (2000, 126, 31); # 초기 히스토리 생성
```
2. Artillery 스크립트 작성
- /bid API 토큰 인증 잠시 무효화
- 요청 body 에 bidPrice 와 customerId 무작위 생성
```yaml
      - post:
          url: "/bid"
          json:
            bidPrice: "{{ $randomInt(2001, 3000) }}"
            customerId: "{{ $randomInt(26, 125) }}"
            productId: 31
```
#### 문제해결
- bidPrice 와 customerId 가 0 과 null 로 전달되어 테스트 실패 → csv 파일로 요청하여 해결
```console
productBidDto: ProductBidDto(id=null, bidPrice=0, customerId=null, customerEmail=null, productId=31) 
```

- 분산 환경에서 동시 요청한 경우 가장 큰 값이 아닌 가격이 등록되는 이슈 확인

![Image](https://github.com/user-attachments/assets/16814735-6332-48f2-9713-46b8919e0943)
