### ISSUE TITLE
모니터링을 위한 actuator 와 prometheus 적용 with Slack

### ISSUE THREAD

**Issue by dlask913** [dlask913/vue3-spring-project#39]
> 1. actuator 와 prometheus 를 통한 메트릭 수집 
> 2. 운영을 고려한 모니터링 지표 선정 -> 서버 다운, 응답시간 지연, 메모리 부족, CPU 사용량
> 3. Slack 연동하여 위 Alert status 가 FIRING 인 경우 알림 보내기

<br>

## actuator 적용
1. dependency 추가
```gradle 
implementation 'org.springframework.boot:spring-boot-starter-actuator'
```
2. 포트 분리 및 엔드포인트 설정
- 애플리케이션 내부 정보를 너무 많이 노출하기 때문에 포트 분리
- `/actuator/health` : 시스템 상태 (디스크, DB 등 포함 가능)
- `/actuator/info` : 앱 정보 (버전, 환경 등)
- `/actuator/metrics` : 다양한 메트릭 (JVM, CPU, HTTP, DB 등)
- `/actuator/metrics/jvm.memory.used` : JVM 메모리 사용량
- `/actuator/metrics/system.cpu.usage` : 시스템 CPU 사용률
- `/actuator/metrics/http.server.requests` : HTTP 요청 처리 시간 및 횟수
- `/actuator/threaddump` : 쓰레드 상태 확인
- `/actuator/heapdump` : 힙 메모리 덤프

<br>

## 프로메테우스
1. dependency 추가
```gradle
implementation 'io.micrometer:micrometer-registry-prometheus'
```

2. 메트릭 수집 설정
- /actuator/prometheus 를 호출해서 메트릭을 주기적으로 수집하도록 설정
- application.yml 파일에 promethus endpotints 활성화
```yml
management:
  server:
    port: 9292
  endpoints:
    web:
      exposure:
        include: prometheus
```

3. prometheus.yml 에 jobs 추가
```yml
scrape_configs:
  - job_name: "spring-actuator"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ["localhost:9292"]
```

4. prometheus.exe 실행하여 localhost:9090 에서 상태확인 ( Status > Targets )

<img width="1705" height="445" alt="Image" src="https://github.com/user-attachments/assets/aa7635da-ad5f-4b4c-984f-58ec5018de84" />

<br>

#### 응답시간 지연 테스트
```java
    @GetMapping("/slow")
    public String slow() throws InterruptedException {
        Thread.sleep(5000); // 5초
        return "done";
    }
```

<img width="1705" height="402" alt="Image" src="https://github.com/user-attachments/assets/95be67f4-2da9-4e96-ba42-dc69920af227" />

#### 메모리 부족 테스트 
```java 
    @GetMapping("/oom")
    public void oom() {
        List<byte[]> list = new ArrayList<>();
        while (true) {
            list.add(new byte[50* 1024 * 1024]); // 50MB
        }
    }
```

<img width="1723" height="393" alt="Image" src="https://github.com/user-attachments/assets/dc843389-d126-4ab6-ac5c-01adf590032b" />

#### CPU 사용량 테스트
- 잘 안 올라가서 탭 10개 이상 띄우고 /cpu 호출하여 확인
```java
    @GetMapping("/cpu")
    public String highCpu() {
        long end = System.currentTimeMillis() + 60000; // 60초 동안 CPU 태움
        while (System.currentTimeMillis() < end) {
            Math.pow(Math.random(), Math.random());
        }
        return "CPU test done 960 seconds)";
    }
```

<img width="1834" height="391" alt="Image" src="https://github.com/user-attachments/assets/9b116191-54c6-4f4c-a8f3-7f4418e2eb7a" />

<br> 
<br> 

## alertmanager 연동 
- slack 알림을 위해 alertmanager 연동 ( [공식문서](https://prometheus.io/download/) )
- api_url 필드에 Slack webhook url 설정 

<br>

#### Slack 알림이 오지 않는 문제 
- alertmanager.exe 콘솔창에서 로그 확인해보니 #monitoring 채널이 없어서라는 원인 발견
```console
time=2025-12-16T21:46:22.065+09:00 level=ERROR source=dispatch.go:363 msg="Notify for alerts failed" component=dispatcher num_alerts=1 err="slack/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"#monitoring\": unexpected status code 404: channel_not_found"
ti
```
#### 해결
- alertmanager.yml 의 slack receiver 항목에서 channel 탭 제거 
```yml
receivers:
  - name: 'slack'
    slack_configs:
      - api_url: 'api-url'
#        channel: '#monitoring'
        send_resolved: true
```

<br>

#### 실행 결과

<img width="2630" height="729" alt="Image" src="https://github.com/user-attachments/assets/585f5341-3b45-4ca9-bf70-3ca9996a8461" />
